name: medialerta
description: Aplicativo para controle de medicamentos.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.7
  intl: ^0.19.0
  sqflite: ^2.3.3
  path: ^1.9.0
  cupertino_icons: ^1.0.8
  scroll_to_index: ^3.0.1
  dropdown_button2: ^2.3.9
  flutter_local_notifications: ^19.4.0
  timezone: ^0.10.0
  path_provider: ^2.1.5
  shared_preferences: ^2.2.3  
  android_alarm_manager_plus: ^4.0.8  
  just_audio: ^0.10.4
  flutter_isolate: ^2.0.4
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  image_path: "assets/icone_ma.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/imagem_senhora.png
    - assets/icone_ma.png   
    - assets/qr_pix.png
    - assets/sounds/alarm.mp3
    - assets/sounds/alert.mp3
    - assets/sounds/malta.mp3
    - assets/sounds/simple.mp3
    - assets/sounds/violin.mp3

